Less task
accendino/dz-gulp-1 pull request #1
Opened 2018-07-30 18:47 UTC by accendino

Удалила лишнее, оставили таск less для компиляции less файлов (С ОШИБКАМИ для практики).

2018-07-30 19:01 UTC, nobleworkshop requested changes
12-я строка слежение за sass, хотя вроде в проекте less

4-я строка - удаляем sass полностью

2018-07-30 19:41 UTC, accendino commented
@nobleworkshop , внесла изменения)

2018-07-30 23:20 UTC, nobleworkshop requested changes
Есть один момент, поправить. Комментарий в коде.

2018-07-30 23:20 UTC, nobleworkshop commented on gulpfile.js
> +var styles = require('gulp-less');
Тут все таки стоит оставлять название переменной как less.

2018-07-30 23:20 UTC, nobleworkshop commented on gulpfile.js
> +var styles = require('gulp-less');
И далее по коду надо будет также внести изменения.

2018-07-31 05:44 UTC, accendino commented on gulpfile.js
> +var styles = require('gulp-less');
разве в домашке не styles просили прописывать? ок!

2018-07-31 06:23 UTC, accendino commented
back to less :)

2018-07-31 09:33 UTC, nobleworkshop approved these changes
Хорошо!) Теперь все верно!)

2018-07-31 15:37 UTC, merged